[package]
name = "challenge_1"
version = "0.1.0"
authors = ["Danny <36959138+DannyStoyanov@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
